package hueclient

type LightArchetype string

const (
	ArchetypeUnknownArchetype    LightArchetype = "unknown_archetype"
	ArchetypeClassicBulb         LightArchetype = "classic_bulb"
	ArchetypeSultanBulb          LightArchetype = "sultan_bulb"
	ArchetypeFloodBulb           LightArchetype = "flood_bulb"
	ArchetypeSpotBulb            LightArchetype = "spot_bulb"
	ArchetypeCandleBulb          LightArchetype = "candle_bulb"
	ArchetypeLusterBulb          LightArchetype = "luster_bulb"
	ArchetypePendantRound        LightArchetype = "pendant_round"
	ArchetypePendantLong         LightArchetype = "pendant_long"
	ArchetypeCeilingRound        LightArchetype = "ceiling_round"
	ArchetypeCeilingSquare       LightArchetype = "ceiling_square"
	ArchetypeFloorShade          LightArchetype = "floor_shade"
	ArchetypeFloorLantern        LightArchetype = "floor_lantern"
	ArchetypeTableShade          LightArchetype = "table_shade"
	ArchetypeRecessedCeiling     LightArchetype = "recessed_ceiling"
	ArchetypeRecessedFloor       LightArchetype = "recessed_floor"
	ArchetypeSingleSpot          LightArchetype = "single_spot"
	ArchetypeDoubleSpot          LightArchetype = "double_spot"
	ArchetypeTableWash           LightArchetype = "table_wash"
	ArchetypeWallLantern         LightArchetype = "wall_lantern"
	ArchetypeWallShade           LightArchetype = "wall_shade"
	ArchetypeFlexibleLamp        LightArchetype = "flexible_lamp"
	ArchetypeGroundSpot          LightArchetype = "ground_spot"
	ArchetypeWallSpot            LightArchetype = "wall_spot"
	ArchetypePlug                LightArchetype = "plug"
	ArchetypeHueGo               LightArchetype = "hue_go"
	ArchetypeHueLightstrip       LightArchetype = "hue_lightstrip"
	ArchetypeHueIris             LightArchetype = "hue_iris"
	ArchetypeHueBloom            LightArchetype = "hue_bloom"
	ArchetypeBollard             LightArchetype = "bollard"
	ArchetypeWallWasher          LightArchetype = "wall_washer"
	ArchetypeHuePlay             LightArchetype = "hue_play"
	ArchetypeVintageBulb         LightArchetype = "vintage_bulb"
	ArchetypeVintageCandleBulb   LightArchetype = "vintage_candle_bulb"
	ArchetypeEllipseBulb         LightArchetype = "ellipse_bulb"
	ArchetypeTriangleBulb        LightArchetype = "triangle_bulb"
	ArchetypeSmallGlobeBulb      LightArchetype = "small_globe_bulb"
	ArchetypeLargeGlobeBulb      LightArchetype = "large_globe_bulb"
	ArchetypeEdisonBulb          LightArchetype = "edison_bulb"
	ArchetypeChristmasTree       LightArchetype = "christmas_tree"
	ArchetypeStringLight         LightArchetype = "string_light"
	ArchetypeHueCentris          LightArchetype = "hue_centris"
	ArchetypeHueLightstripTV     LightArchetype = "hue_lightstrip_tv"
	ArchetypeHueLightstripPC     LightArchetype = "hue_lightstrip_pc"
	ArchetypeHueTube             LightArchetype = "hue_tube"
	ArchetypeHueSigne            LightArchetype = "hue_signe"
	ArchetypePendantSpot         LightArchetype = "pendant_spot"
	ArchetypeCeilingHorizontal   LightArchetype = "ceiling_horizontal"
	ArchetypeCeilingTube         LightArchetype = "ceiling_tube"
	ArchetypeUpAndDown           LightArchetype = "up_and_down"
	ArchetypeUpAndDownUp         LightArchetype = "up_and_down_up"
	ArchetypeUpAndDownDown       LightArchetype = "up_and_down_down"
	ArchetypeHueFloodlightCamera LightArchetype = "hue_floodlight_camera"
	ArchetypeTwilight            LightArchetype = "twilight"
	ArchetypeTwilightFront       LightArchetype = "twilight_front"
	ArchetypeTwilightBack        LightArchetype = "twilight_back"
	ArchetypeHuePlayWallwasher   LightArchetype = "hue_play_wallwasher"
	ArchetypeHueOmniglow         LightArchetype = "hue_omniglow"
	ArchetypeHueNeon             LightArchetype = "hue_neon"
	ArchetypeStringGlobe         LightArchetype = "string_globe"
	ArchetypeStringPermanen      LightArchetype = "string_permanen"
)
